# Generated by Django 5.2 on 2026-05-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('RULE_ID_NBR', models.CharField(db_column='RULE-ID-NBR', max_length=50, null=True)),
                ('MACRO_RULE', models.CharField(max_length=255, null=True)),
                ('RULE_TYPE', models.CharField(db_column='RULE-TYPE', max_length=50, null=True)),
                ('RULE_REGN', models.CharField(db_column='RULE-REGN', max_length=50, null=True)),
                ('RULE_NAME', models.CharField(db_column='RULE-NAME', max_length=255, null=True)),
                ('MCRFM_ROLL_CD', models.CharField(db_column='MCRFM-ROLL-CD', max_length=50, null=True)),
                ('INDIV_SEQ_NBR', models.CharField(db_column='INDIV-SEQ-NBR', max_length=50, null=True)),
                ('ENRL_CERT_NBR', models.CharField(db_column='ENRL-CERT-NBR', max_length=50, null=True)),
                ('ACTV_DT', models.DateField(db_column='ACTV-DT', null=True)),
                ('SERV_RCVD_DT', models.DateField(db_column='SERV-RCVD-DT', null=True)),
                ('SERV_CMPL_DT', models.DateField(db_column='SERV-CMPL-DT', null=True)),
                ('CHRG_AMT', models.DecimalField(db_column='CHRG-AMT', decimal_places=2, max_digits=12, null=True)),
                ('PMT_AMT', models.DecimalField(db_column='PMT-AMT', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'TBL_DAILY_INVENTORY_NEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claims_id', models.CharField(max_length=255)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('manual', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('rule_engine_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'claims_data',
            },
        ),
        migrations.CreateModel(
            name='ParamModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_group_id', models.IntegerField()),
                ('param_name', models.CharField(max_length=255)),
                ('param_type', models.CharField(max_length=50)),
                ('param_options', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'param_model',
            },
        ),
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('reactflow_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_engine',
            },
        ),
        migrations.CreateModel(
            name='RuleEngineProcessed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_engine_id', models.IntegerField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField()),
                ('claims_count', models.IntegerField()),
            ],
            options={
                'db_table': 'rule_engine_processed',
            },
        ),
        migrations.CreateModel(
            name='RuleLogic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=255)),
                ('input_params', models.IntegerField(blank=True, null=True)),
                ('output_params', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_logic',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, unique=True)),
                ('combinations', models.JSONField(blank=True, null=True)),
                ('schedule_config', models.JSONField(blank=True, null=True)),
                ('rule_id', models.IntegerField(blank=True, help_text='Must match RuleEngine.id exactly', null=True)),
                ('rule_name', models.CharField(help_text='Must match RuleEngine.rule_name exactly', max_length=255)),
                ('interval', models.PositiveIntegerField(blank=True, help_text='How often to run (numeric value)', null=True)),
                ('unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours')], default='seconds', help_text='Unit for the interval', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Job',
                'verbose_name_plural': 'Scheduled Jobs',
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='RuleList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(help_text='Reference to RuleLogic.function_name (string, not a foreign key)', max_length=255)),
                ('rule_function_order', models.IntegerField()),
                ('params', models.JSONField(default=dict)),
                ('rule_engine', models.ForeignKey(db_column='rule_engine_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.ruleengine')),
            ],
            options={
                'db_table': 'rule_list',
                'ordering': ['rule_function_order'],
            },
        ),
        migrations.CreateModel(
            name='RuleEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='rule_engine.ruleengine')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='rule_engine.rulelist')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='rule_engine.rulelist')),
            ],
        ),
    ]
