# Generated by Django 6.0.2 on 2026-02-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_group_id', models.IntegerField()),
                ('param_name', models.CharField(max_length=255)),
                ('param_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'param_model',
            },
        ),
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reactflow_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_engine',
            },
        ),
        migrations.CreateModel(
            name='RuleLogic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=255)),
                ('input_params', models.IntegerField()),
                ('output_params', models.IntegerField()),
            ],
            options={
                'db_table': 'rule_logic',
            },
        ),
        migrations.CreateModel(
            name='RuleEngineProcessed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField()),
                ('rule_engine', models.ForeignKey(db_column='rule_engine_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.ruleengine')),
            ],
            options={
                'db_table': 'rule_engine_processed',
            },
        ),
        migrations.CreateModel(
            name='RuleList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_function_order', models.IntegerField()),
                ('params', models.JSONField(default=dict)),
                ('rule_engine', models.ForeignKey(db_column='rule_engine_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.ruleengine')),
                ('rule_logic', models.ForeignKey(db_column='rule_logic_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.rulelogic')),
            ],
            options={
                'db_table': 'rule_list',
                'ordering': ['rule_function_order'],
            },
        ),
    ]
