# Generated by Django 6.0.2 on 2026-02-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='rule_engine.ruleengine')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='rule_engine.rulelist')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='rule_engine.rulelist')),
            ],
        ),
    ]
