# Generated by Django 5.2.11 on 2026-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_ruleedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('RULE_ID_NBR', models.CharField(db_column='RULE-ID-NBR', max_length=50, null=True)),
                ('MACRO_RULE', models.CharField(max_length=255, null=True)),
                ('RULE_TYPE', models.CharField(db_column='RULE-TYPE', max_length=50, null=True)),
                ('RULE_REGN', models.CharField(db_column='RULE-REGN', max_length=50, null=True)),
                ('RULE_NAME', models.CharField(db_column='RULE-NAME', max_length=255, null=True)),
                ('MCRFM_ROLL_CD', models.CharField(db_column='MCRFM-ROLL-CD', max_length=50, null=True)),
                ('ACTV_DT', models.DateField(db_column='ACTV-DT', null=True)),
                ('SERV_RCVD_DT', models.DateField(db_column='SERV-RCVD-DT', null=True)),
                ('SERV_CMPL_DT', models.DateField(db_column='SERV-CMPL-DT', null=True)),
                ('CHRG_AMT', models.DecimalField(db_column='CHRG-AMT', decimal_places=2, max_digits=12, null=True)),
                ('PMT_AMT', models.DecimalField(db_column='PMT-AMT', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'TBL_DAILY_INVENTORY_NEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claims_id', models.CharField(max_length=255)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('manual', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('rule_engine_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'claims_data',
            },
        ),
        migrations.AddField(
            model_name='ruleengineprocessed',
            name='claims_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruleedge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rulelogic',
            name='input_params',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rulelogic',
            name='output_params',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
