# Generated by Django 5.2.11 on 2026-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_dailyinventory_claimsdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Must match RuleEngine.rule_name exactly', max_length=255, unique=True)),
                ('interval', models.PositiveIntegerField(help_text='How often to run (numeric value)')),
                ('unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours')], default='seconds', help_text='Unit for the interval', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Job',
                'verbose_name_plural': 'Scheduled Jobs',
                'ordering': ['rule_name'],
            },
        ),
    ]
