# Generated by Django 5.2 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_parammodel_param_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsdata',
            name='decision',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
