# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0004_claimsdata_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsdata',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
