# Generated by Django 5.2.11 on 2026-03-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0004_scheduledjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleengine',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleengine',
            name='rule_engine_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
