# Generated by Django 5.2.11 on 2026-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0005_ruleengine_deleted_ruleengine_rule_engine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleengine',
            name='rule_engine_id',
        ),
        migrations.RemoveField(
            model_name='ruleengineprocessed',
            name='rule_engine',
        ),
        migrations.AddField(
            model_name='ruleengineprocessed',
            name='rule_engine_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruleengineprocessed',
            name='rule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='schedule_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval'), ('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('cron', 'Cron')], default='cron', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruleengine',
            name='rule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
