# Generated by Django 5.2.11 on 2026-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0006_remove_ruleengine_rule_engine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='schedule_config',
        ),
        migrations.RemoveField(
            model_name='scheduledjob',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='rule_id',
            field=models.IntegerField(blank=True, help_text='Must match RuleEngine.id exactly', null=True),
        ),
    ]
