# Generated by Django 5.2.11 on 2026-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0007_remove_scheduledjob_schedule_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='combinations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
