# Generated by Django 5.2.11 on 2026-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0008_scheduledjob_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='schedule_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
