# Generated by Django 5.2.11 on 2026-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0009_scheduledjob_schedule_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='interval',
            field=models.PositiveIntegerField(blank=True, help_text='How often to run (numeric value)', null=True),
        ),
    ]
