# Generated by Django 5.2.11 on 2026-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0010_alter_scheduledjob_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='job_name',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='rule_name',
            field=models.CharField(help_text='Must match RuleEngine.rule_name exactly', max_length=255),
        ),
    ]
